# Generated by Django 6.0.5 on 2026-05-22 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField()),
                ('numero_documento', models.CharField(max_length=100)),
                ('documento_ingreso', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('codigo_numerico', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_dcto_estado', models.CharField(blank=True, max_length=150, null=True)),
                ('responsable', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=20)),
                ('documento_adjunto', models.FileField(blank=True, null=True, upload_to='returns/documentos/')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='returns/fotos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_recepcion', '-creado_en'],
            },
        ),
    ]
