# Generated by Django 6.0.5 on 2026-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-fecha_recepcion', '-creado_en'], 'verbose_name': 'Devolución', 'verbose_name_plural': 'Devoluciones'},
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='documento_ingreso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Documento de ingreso / NC cliente'),
        ),
    ]
