# Generated by Django 6.0.5 on 2026-05-22 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_alter_returnrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='fecha_respuesta_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha respuesta cliente'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='respuesta_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Respuesta del cliente'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado en'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='cliente',
            field=models.CharField(max_length=150, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='codigo_numerico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Numérico'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='documento_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='returns/documentos/', verbose_name='Documento adjunto'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Fecha Recepción'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='returns/fotos/', verbose_name='Foto evidencia'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='numero_dcto_estado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='N° Dcto/Estado'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='numero_documento',
            field=models.CharField(max_length=100, verbose_name='N° Documento'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='sku',
            field=models.CharField(max_length=100, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación'),
        ),
    ]
