# Generated by Django 6.0.5 on 2026-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnrequest_fecha_respuesta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='documento_respuesta_cliente',
            field=models.FileField(blank=True, null=True, upload_to='returns/respuestas/documentos/', verbose_name='Documento adjunto cliente'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='fecha_adjuntos_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha adjuntos cliente'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='fecha_en_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en revisión'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='fecha_observacion_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha observación cliente'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='foto_respuesta_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='returns/respuestas/fotos/', verbose_name='Foto evidencia cliente'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='respuesta_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del cliente'),
        ),
    ]
