# Generated by Django 6.0.5 on 2026-05-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0004_returnrequest_documento_respuesta_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='fecha_aprobacion_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha aprobación cliente'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='fecha_rechazo_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha rechazo cliente'),
        ),
    ]
