# Generated by Django 6.0.5 on 2026-05-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0007_returnrequest_cerrado_por_returnrequest_fecha_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='returns/adjuntos/', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('DOCUMENTO_INTERNO', 'Documento interno'), ('FOTO_INTERNA', 'Foto interna'), ('DOCUMENTO_CLIENTE', 'Documento cliente'), ('FOTO_CLIENTE', 'Foto cliente')], max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='returns.returnrequest')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto devolución',
                'verbose_name_plural': 'Adjuntos devoluciones',
                'ordering': ['creado_en'],
            },
        ),
    ]
