# Generated by Django 6.0.5 on 2026-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0008_returnrequestattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('OBSERVADO', 'Pendiente corrección'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], default='RECIBIDO', max_length=20, verbose_name='Estado'),
        ),
    ]
