# Generated by Django 6.0.5 on 2026-06-21 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0009_alter_returnrequest_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=150, verbose_name='Serie')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_devoluciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='returns.returnrequest', verbose_name='Devolución')),
            ],
            options={
                'verbose_name': 'Serie de devolución',
                'verbose_name_plural': 'Series de devoluciones',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('return_request', 'serie'), name='unique_return_request_serie')],
            },
        ),
    ]
