# Generated by Django 6.0.5 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0010_returnrequestserial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='returnrequestserial',
            name='unique_return_request_serie',
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='codigo_numerico',
            field=models.TextField(blank=True, null=True, verbose_name='Código Numérico'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='documento_ingreso',
            field=models.TextField(blank=True, null=True, verbose_name='Documento de ingreso / NC cliente'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='numero_dcto_estado',
            field=models.TextField(blank=True, null=True, verbose_name='Estado de Inventario'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='numero_documento',
            field=models.TextField(verbose_name='N° Documento'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='serie',
            field=models.TextField(blank=True, null=True, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='returnrequestserial',
            name='serie',
            field=models.TextField(verbose_name='Serie'),
        ),
    ]
